### ISSUE TITLE
Autorunrecord can't output tree 

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#49]
``autorunrecord`` crashes when trying to display the characters the ``tree`` command produces.

Example:

```rst

.. runrecord:: _examples/DL-101-5
  :language: console
  :realcommand: cd DataLad-101 && tree

   $ tree
```

leads to this traceback:

```sh

Traceback (most recent call last):
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/io.py", line 325, in read_doc
    pub.publish()
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/io.py", line 113, in read
    self.parse()
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 1150, in indent
    elements = self.block_quote(indented, line_offset)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 1165, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/adina/env/handbook/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/adina/repos/autorunrecord/sphinxcontrib/autorunrecord.py", line 56, in run
    self.capture_output(capture_file, work_dir)
  File "/home/adina/repos/autorunrecord/sphinxcontrib/autorunrecord.py", line 99, in capture_output
    stdout.decode(output_encoding),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)

Encoding error:
'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-t91drlnv.log, if you want to report the issue to the developers.
make[1]: *** [Makefile:50: html] Error 2
make[1]: Leaving directory '/home/adina/repos/datalad-handbook/docs'
make: *** [Makefile:7: html] Error 2

```

Currently, I'm working around this with `` ..code-block:: bash``.

**Comment by mih** [comment]
Looking into it

**Comment by mih** [comment]
I have made a new release (v0.2) of the autorunrecord sphinx extension that now uses `utf-8` encoding by default. This should fix it. 

`pip install autorunrecord -U`

**Comment by mih** [comment]
Hey, @all-contributors, please add @adswa for this bug report
